name: smart_batching
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  animated_splash_screen: ^1.3.0
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.4.2
  firebase_core: ^2.10.0
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.5.3+2
  flutter_svg: ^2.0.5
  font_awesome_flutter: ^10.1.0
  sign_button: ^2.0.2
  url_launcher: ^6.1.4
  animated_text_kit: ^4.2.2
  flutter_native_splash: ^2.2.8
  google_fonts: ^4.0.4
  cloud_firestore: ^4.5.3
  google_sign_in: ^6.1.0
  flutter_neumorphic: ^3.2.0
  dot_navigation_bar: ^1.0.1+4
  csc_picker: ^0.2.6
  path_provider: ^2.0.11
  provider: ^6.0.3
  firebase_storage: ^11.1.1
  search_page: ^2.0.0+1
  location: ^4.4.0
  rename: ^2.0.1
  animations: ^2.0.4
  double_back_to_close_app: ^2.1.0
  animate_do: ^3.0.2
  google_nav_bar: ^5.0.6

dev_dependencies:

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo_login.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/logo_login.png"
    background_color: "#f5f6f9"
    theme_color: "#f5f6f9"
  windows:
    generate: true
    image_path: "assets/logo_login.png"
    icon_size: 48 # min:48, max:256, default: 48

flutter:
  uses-material-design: true

  assets:
    - assets/